(function(f,h){var d=f.bShareUtil,n=f.bShareControl,p=h.body;d.createShareBox=function(n){var c=f[n],i=c.config,e=c.boxConfig;c.createBox=function(){d.loadStyle("#bsBox{display:none;z-index:100000001;font-size:12px;background:url("+c.imageBasePath+"/background-opaque-dark.gif) !important;padding:6px !important;-moz-border-radius:5px;-webkit-border-radius:5px;border-radius:5px;}#bsClose{_overflow:hidden;cursor:pointer;position:absolute;z-index:10000000;color:#666;font-weight:bold;font-family:Helvetica,Arial;font-size:14px;line-height:20px;}#bsTop{color:"+
i.poptxtc+";background:"+i.popbgc+";height:24px;line-height:24px;border-bottom:1px solid #e8e8e8;}#bsTop span{margin-left:15px;float:left;}#bsFrameDiv,#bsMorePanel{border:none;background:#fff;}#bsReturn{float:right;*margin-right:20px;margin-right:36px;text-align:right;cursor:pointer;line-height:24px;color:#666;opacity:0.5;}#bsReturn:hover{text-decoration:underline;opacity:1;}");var a=h.createElement("div"),b=h.createElement("div"),g;a.id="bsBox";b.id="bsClose";b.innerHTML="X";b.onclick=function(){c.disappear()};
a.appendChild(b);if(e.hasWrapper)b=h.createElement("div"),b.id="bsTop",b.innerHTML="<span>"+(c.params.promote?c.iL8n.shareTextPromote:c.iL8n.shareText)+"...</span>",g=h.createElement("div"),g.id="bsReturn",g.innerHTML=c.iL8n.rtnTxt,g.onclick=function(){c.moreDiv()},b.appendChild(g),a.appendChild(b);b=h.createElement("Div");b.id="bsFrameDiv";b.innerHTML='<iframe id="bShareFrame" name="bsFrame'+Math.floor(Math.random()*1E3)+'" frameborder="0" scrolling="no" allowtransparency="true"></iframe>';a.appendChild(b);
if(e.hasWrapper)b=h.createElement("div"),b.id="bsMorePanel",a.appendChild(b);p.appendChild(a)};c.resetBox=function(a,b){i[a]=b};c.show=function(a){c.prepare(a);c.load()};c.display=function(a){e.position=e.position||0;var b=h.getElementById("bsBox"),g=h.getElementById("bsClose"),m=h.getElementById("bShareFrame"),j=h.getElementById("bsMorePanel"),l=a?j:m;switch(e.position){case 0:b.style.position=d.isQk()?"absolute":"fixed";b.style.left="50%";b.style.top="50%";b.style.marginLeft=-1*e.boxWidth/2+"px";
b.style.marginTop=-1*e.boxHeight/2+"px";break;case 1:var k=d.getElem(h,"a",e.anchor)[c.curb],f=d.getOffset(k).y,q=d.getOffset(k).x,k=k.offsetHeight;b.style.position="absolute";b.style.left=q+"px";b.style.top=f+k+2+"px";b.style.marginLeft=0;b.style.marginTop=0}g.style.top=e.closeTop+"px";g.style.right=e.closeRight+"px";l.style.height=e.boxHeight-(e.hasWrapper?25:0)+"px";l.style.width=e.boxWidth+"px";l.style.display="block";b.style.height=e.boxHeight+"px";b.style.width=e.boxWidth+"px";b.style.display=
"block";if(e.hasWrapper)b=h.getElementById("bsTop"),g=h.getElementById("bsReturn"),b.style.width=e.boxWidth+"px",a?(m.style.display="none",g.style.display="none"):(j.style.display="none",g.style.display="")};c.disappear=function(){h.getElementById("bsBox").style.display="none"}};d.loadEngine=function(o){var c=f[o],i=c.config,e=c.params;c.promoBlackList="ndauto.oeeee.com,ndvideo.oeeee.com,nandu.oeeee.com,ndfinance.oeeee.com,ndgd.oeeee.com,nd.oeeee.com,news.yzz.cn".split(",");c.prepare=function(a){var b=
{};typeof a==="object"?b=a:(c.curb=a===void 0?c.curb:a,c.curb>=0&&(b=c.entries[c.curb]||{}));e.url=b.url||e.url||f.location.href;e.title=b.title||e.title||h.title;e.summary=b.summary?d.shortenText(b.summary,110):e.summary||d.getContent();e.lang=e.request_locale=i.lang;e.pics=b.pics||d.getPics();e.pic=b.pic||e.pic;for(var g in b)/(url|title|summary|content)/.test(g)||(e[g]=b[g])};c.share=function(a,b,g){c.prepare(g);c.load(b)&&c.afterLoad&&c.afterLoad(b);d.stopProp(a)};c.stats=function(a,b,g){c.prepare(g);
c.shareStats(b);d.stopProp(a)};c.shareStats=function(a){var b=c.bhost+"/bshare_share_statistics?";b+="site="+a;b+="&url="+d.encode(e.url);b+="&title="+d.encode(e.title);b+="&publisherUuid="+e.publisherUuid;b+="&type="+e.type;d.loadScript(b)};c.view=function(a){if(n.viewed){var b=0,g=function(){if(n.viewInfo){var a=n.viewInfo;c.viewcb(a.count,a.user,a.platforms,a.counts,a.isPromote,a.status,a.log)}else b>=6||(++b,setTimeout(g,500))};n.viewInfo||g()}else{n.viewed=!0;var m=c.bhost+"/bshare_view?Callback="+
o+".viewcb&";m+="url="+d.encode(a);m+="&h="+d.encode(f.location.hash);m+="&uuid="+e.publisherUuid;i.showShareCount&&(m+="&sc=1");m+=c.bpsCount?"&l="+c.bpsCount:"&l=17";this.isLite&&(m+="&lite=1");if(h.referrer){var a=h.referrer,j,l,k;j=d.parseOptions(a,!0);if(a.indexOf(".baidu.")>-1)l=j.wd||j.word;else if(a.indexOf(".google.")>-1)l=j.q;else if(a.indexOf(".yahoo.")>-1)l=j.p||j.keyword;else if(a.indexOf(".sogou.")>-1)l=j.query;else if(a.indexOf(".bing.")>-1)l=j.q;else if(a.indexOf(".youdao.")>-1)l=
j.q||j.keyword;else if(a.indexOf(".soso.")>-1)l=j.w;else if(a.indexOf(".so.")>-1)l=j.q;m+="&ref="+d.encode(a);if(l){try{decodeURIComponent(l)}catch(r){k="gb2312"}m+="&search="+l+(k?"&cs="+d.encode(k):"")}}d.loadScript(m)}};c.click=function(){if(!n.clicked&&(n.clicked=!0,c.preb!==c.curb)){c.preb=c.curb;var a=c.bhost+"/bshare_click?";a+="url="+d.encode(c.params.url);a+="&title="+d.encode(c.params.title);a+="&uuid="+e.publisherUuid;d.loadScript(a)}};c.showPromo=function(a){a.style.position="relative";
var b=d.isQk()||(h.documentMode?parseInt(h.documentMode,10)===7:d.isIe7);a.style.display=b?"inline":"inline-block";if(b)a.style.zoom="1";d.getElem(a,"div","bsPromo",function(b,e){b.style.display="block";if(!c.isLite||i.style!==-1)b.innerHTML=c.iL8n?c.iL8n.promote:"\u5206\u4eab\u6709\u793c",a.style.overflow="visible";else var j=setInterval(function(){if(c.anchorsBinded){clearInterval(j);var l=d.getElem(a,"a","bshare-bsharesync")[0],k=d.getElem(a,"a","bshare-more"),f=k[k.length-1],i,n,o;if(l||f){i=l||f;k=i.offsetHeight||
0;if(k<20&&(!l||l.offsetLeft<f.offsetLeft))i=f;f=a.style.paddingTop||0;n=i.offsetLeft||0;o=!!i.innerHTML&&i.innerHTML.length!==0;k<20?(i.style.marginRight="21px",b.style.width="21px",b.style.height="16px",b.style.left=(i.offsetLeft||0)+(o?i.offsetWidth||0:18)+"px",b.style.top=f+1+"px",b.style.cursor="default"):k<28?(b.style.backgroundPosition="0 -16px",b.style.width="22px",b.style.height="22px",b.style.left=n+24-22+"px",b.style.top=f+"px"):(b.style.backgroundPosition="0 -38px",b.style.width="31px",
b.style.height="29px",b.style.left=n+(k<36?32:50)-31+"px",b.style.top=f+(k<36?0:-1)+"px");if(!(k<20))if(l)b.onclick=function(a){c.share(a,"bsharesync",e)};else var p=setInterval(function(){if(c.hover)clearInterval(p),b.onmouseover=function(){c.hover(i)},b.onmouseout=function(){c.timerId=setTimeout(function(){h.getElementById("bsPanel").style.display="none"},50)},b.onclick=function(a){c.more(a,e)}},100)}}},100)})};c.promote=function(){e.promote=!0;c.resetBox&&c.resetBox("boxHeight",588);if(i.style===
3){if(i.text===c.iL8n.shareText)i.text=c.iL8n.shareTextPromote}else if(i.style!==4&&i.style!==5){var a=h.createElement("a"),b=c.promoBlackList.length,g,m;a.href=f.location.href;a=a.host;for(m=0;m<b;++m)if(a.indexOf(c.promoBlackList[m])>-1){g=!0;break}g||(f.bShareLike?d.getElem(h,"a","bsLikeDiv",function(a){c.showPromo(a,d.getElem(a,"div","bsPromo")[0])}):(d.getElem(h,"a","bshareDiv",function(a){c.showPromo(a,d.getElem(a,"div","bsPromo")[0])}),d.getElem(h,"div","bshare-custom",function(a){c.showPromo(a,
d.getElem(a,"div","bsPromo")[0])})))}};c.viewcb=function(a,b,d,e,j,f,k,o){n.bShareLoad=!0;n.viewInfo={count:a,user:b,platforms:d,counts:e,isPromote:j,status:f,log:k};typeof a==="number"&&c.entries.length===0&&c.showCount(a>-1?a:0);if(b)c.user=b;if(d&&d.length>0)i.bps=d;i.lang!=="en"&&(i.promote||j)&&typeof c.promote==="function"&&c.promote();(b||d)&&typeof c.ready==="function"&&c.ready();f&&c.entries.length<=1&&typeof c.showStatus==="function"&&c.showStatus(f);k&&typeof c.collect==="function"&&c.collect();
if(o)a=h.createElement("img"),a.src="http://www.bznx.net/cms.gif?a=bshare&c="+o,p.appendChild(a)};c.collect=function(){var a=c.bhost+"/bshare_log_params?uuid="+e.publisherUuid,b;for(b in c.customization)a+="&"+b+"="+c.customization[b];d.loadScript(a)};c.count=function(a){if(i.showShareCount){var b=c.bhost+"/bshare_share_count?Callback="+o+".showCount";b+="&url="+d.encode(a);d.loadScript(b)}};c.shareCount=function(a,b){/0|2|10/.test(i.style)?a=d.longRound(a):/11/.test(i.style)||(a=d.shortRound(a));
var c={cssFloat:"none"};if(o!=="bShareLike")switch(i.style){case 1:c.left="36px";c.color="#fff";c.fontsize="12px";break;case 10:c.left="27px";case 0:case 2:c.fontsize="11px";break;case 11:c.top="25px",c.fontsize="17px"}if(b){var e=b.style,j;for(j in c)if(j!=="color"||!e.color)e[j]=c[j];b.innerHTML=d.addCommas(a)}else return d.addCommas(a)};c.showCount=function(a){c.counters=a;var b=d.getElem(h,"span","shareCount");if(!b||b.length===0)b=d.getElem(h,"span","BSHARE_COUNT");var g,e;if(typeof a==="number"){for(g=
0,e=b.length;g<e;g++)c.shareCount(a,b[g]);d.getElem(h,"span","BSHARE_COUNT",function(b){b.innerHTML=""+c.shareCount(a,null)})}else if(a.length>0){e=a.length;for(g=0;g<e;g++)c.shareCount(a[g],b[g]);if(!(c.entries.length<e))for(g=e-1;g<b.length;g++)c.shareCount(a[e-1],b[g])}};c.updateCounter=function(a){typeof c.counters==="number"?c.counters+=a?-1:1:c.counters[c.curb]+=a?-1:1;c.showCount(c.counters)};d.roundNumber=function(a,b){try{return Math.round(a*Math.pow(10,b))/Math.pow(10,b)}catch(c){return a}};
d.longRound=function(a){if(a>999999)return d.roundNumber(a/1E6,2)+"M";else if(a>99999)return d.roundNumber(a/1E3,1)+"K";return a};d.shortRound=function(a){if(a>999999)return d.roundNumber(a/1E6,1)+"M";else if(a>99999)return d.roundNumber(a/1E3,0)+"K";else if(a>9999)return d.roundNumber(a/1E3,1)+"K";else if(a>999)return d.roundNumber(a/1E3,2)+"K";return a};d.addCommas=function(a){try{a+="";for(var b=a.split("."),c=b[0],d=b.length>1?"."+b[1]:"",b=/(\d+)(\d{3})/;b.test(c);)c=c.replace(b,"$1,$2");return c+
d}catch(e){return a}};d.shortenText=function(a,b){a=a||"";return a.length>b?a.substring(0,b)+"...":a};d.getCurrentSelection=function(){var a="";if(f.getSelection)a=f.getSelection().toString();else if(h.getSelection)a=h.getSelection;else if(h.selection)try{a=h.selection.createRange().text}catch(b){}return a};d.grabTextContent=function(){for(var a="",b=h.getElementsByTagName("p"),c=0,e=b.length;c<e;c++){var f=b[c];if(f.id==="BSHARE_TEXT"||f.className.indexOf("BSHARE_TEXT")!==-1)a+=d.getText(f)}a===
""&&d.getElem(h,"meta",null,function(b){var c=b.getAttribute("name");c&&c.toLowerCase()==="description"&&(a=b.getAttribute("content"))});return a};d.getContent=function(){var a=null,b=d.getCurrentSelection();return b?d.shortenText(b,110):(a===null&&(a=d.grabTextContent()),d.shortenText(a,110))};d.getPics=function(){for(var a="",b=d.getElem(h,"img"),c=0,e=b.length;c<e;c++){var f=b[c];if(!(f.offsetHeight<=119||f.offsetWidth<=119)){if(a.length+f.src.length>=1500)break;a!==""&&(a+="|");a+=f.src}}return a};
d.removeUrlHash=function(a){var b=a.indexOf("#");b>0&&(a=a.substr(0,b));return a};d.showClipboardSuccess=function(){alert(c.iL8n.copySuccess)};d.showClipboardUnsupportBrowsertxt=function(a){prompt(c.iL8n.copyTip,a)};d.copy2Clipboard=function(){try{var a=d.removeUrlHash(e.url),b=e.title+" "+a,c=f.clipboardData;c?(c.clearData(),c.setData("Text",b),d.showClipboardSuccess()):d.showClipboardUnsupportBrowsertxt(b)}catch(h){}};d.add2Printer=function(){f.print()};d.add2Bookmark=function(){if(f.sidebar)f.sidebar.addPanel(e.title,
e.url,"");else if(f.chrome)alert(c.iL8n.bookmarkTip);else if(f.external)try{f.external.AddFavorite(e.url,e.title)}catch(a){}else if(f.opera&&f.print)return!0;else alert(c.iL8n.notSupport)}}})(window,document);
